export default {
  content: [
    "./index.html",
    "./**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'fc-dark-green': '#2A4535',
        'fc-primary-green': '#4A7C59',
        'fc-medium-sage': '#7DA68D',
        'fc-light-sage': '#F2F8F4',
        'fc-sage-highlight': '#8FB59B',
        'fc-orange-suggestion': '#F4A261',
        'fc-total-card': '#6B9C78',
        "primary": "#0d631b",
        "primary-light": "#cbffc2",
        "accent": "#a3f69c",
        "earth": "#1b6d24",
        "background-light": "#f8faf6",
        "surface-light": "#ffffff",
        "text-main": "#191c1a",
        "text-muted": "#40493d",
        "secondary": "#7a5649",
        "outline": "#707a6c",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#2e150b",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#fabd00",
        "tertiary-fixed": "#ffdf9e",
        "surface-container": "#edeeea",
        "inverse-primary": "#88d982",
        "on-error": "#ffffff",
        "surface-tint": "#1b6d24",
        "surface-container-low": "#f2f4f0",
        "tertiary": "#6d5100",
        "on-surface": "#191c1a",
        "secondary-fixed-dim": "#ebbcac",
        "primary-container": "#2e7d32",
        "surface-variant": "#e1e3df",
        "secondary-container": "#fdcdbc",
        "surface-bright": "#f8faf6",
        "surface-container-high": "#e7e9e5",
        "on-secondary-fixed-variant": "#603f33",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e312f",
        "on-secondary-container": "#795548",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfcaba",
        "tertiary-container": "#8c6800",
        "on-background": "#191c1a",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbcf",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#88d982",
        "primary-fixed": "#a3f69c",
        "inverse-on-surface": "#eff1ed",
        "surface-dim": "#d9dbd7",
        "surface": "#f8faf6",
        "on-tertiary-fixed-variant": "#5b4300",
        "on-surface-variant": "#40493d",
        "background": "#f8faf6",
        "on-primary-fixed": "#002204",
        "on-primary-container": "#cbffc2",
        "surface-container-highest": "#e1e3df",
        "on-tertiary-container": "#ffefd6",
        "on-primary-fixed-variant": "#005312",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "serif": ["Playfair Display", "serif"],
        "script": ["Caveat", "cursive"],
        "headline": ["Lexend", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
          "DEFAULT": "0.5rem",
          "lg": "0.75rem",
          "xl": "1rem",
          "2xl": "1.5rem",
          "3xl": "2.5rem",
          "full": "9999px"
      },
      boxShadow: {
          'premium': '0 10px 30px -10px rgba(27, 67, 50, 0.12)',
          'card-hover': '0 20px 40px -15px rgba(27, 67, 50, 0.15)',
          'soft': '0 10px 40px -5px rgba(42, 69, 53, 0.15)',
      }
    },
  },
  plugins: [],
}
